#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIRC_WA036

#include "Basic.hpp"

#include "BP_AIRefreshConditionBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIRC_WA036.AIRC_WA036_C
// 0x0000 (0x0048 - 0x0048)
class UAIRC_WA036_C final : public UBP_AIRefreshConditionBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AIRC_WA036_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AIRC_WA036_C")
	}
	static class UAIRC_WA036_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIRC_WA036_C>();
	}
};
DUMPER7_ASSERTS_UAIRC_WA036_C;

}

