#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimalControllerBP_Base

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimalControllerBP_Base.AnimalControllerBP_Base_C
// 0x0008 (0x0868 - 0x0860)
class AAnimalControllerBP_Base_C : public AHTNPCController
{
public:
	class UAIPerceptionComponent*                 AIPerception;                                      // 0x0860(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AnimalControllerBP_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimalControllerBP_Base_C")
	}
	static class AAnimalControllerBP_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAnimalControllerBP_Base_C>();
	}
};
DUMPER7_ASSERTS_AAnimalControllerBP_Base_C;

}

