#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Animal_005_Simple_sleep_loop

#include "Basic.hpp"

#include "Animal_005_Simple_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Animal_005_Simple_sleep_loop.Animal_005_Simple_sleep_loop_C
// 0x0000 (0x07A0 - 0x07A0)
class AAnimal_005_Simple_sleep_loop_C final : public AAnimal_005_Simple_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Animal_005_Simple_sleep_loop_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Animal_005_Simple_sleep_loop_C")
	}
	static class AAnimal_005_Simple_sleep_loop_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAnimal_005_Simple_sleep_loop_C>();
	}
};
DUMPER7_ASSERTS_AAnimal_005_Simple_sleep_loop_C;

}

