#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Anomaly_024_AnimBP

#include "Basic.hpp"

#include "NPCAnimBP_Base_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Anomaly_024_AnimBP.Anomaly_024_AnimBP_C
// 0x0010 (0x4340 - 0x4330)
class UAnomaly_024_AnimBP_C final : public UNPCAnimBP_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Anomaly_024_AnimBP_C;               // 0x4330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AnimNotify_CheckWeather();
	void AnimNotify_CheckWeatherEnd();
	void ExecuteUbergraph_Anomaly_024_AnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Anomaly_024_AnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Anomaly_024_AnimBP_C")
	}
	static class UAnomaly_024_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnomaly_024_AnimBP_C>();
	}
};
DUMPER7_ASSERTS_UAnomaly_024_AnimBP_C;

}

