#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Boss_07_ExpandingFieldActor_Skill03

#include "Basic.hpp"


namespace SDK::Params
{

// Function Boss_07_ExpandingFieldActor_Skill03.Boss_07_ExpandingFieldActor_Skill03_C.ExecuteUbergraph_Boss_07_ExpandingFieldActor_Skill03
// 0x0004 (0x0004 - 0x0000)
struct Boss_07_ExpandingFieldActor_Skill03_C_ExecuteUbergraph_Boss_07_ExpandingFieldActor_Skill03 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Boss_07_ExpandingFieldActor_Skill03_C_ExecuteUbergraph_Boss_07_ExpandingFieldActor_Skill03;

}

