#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AIBubble_Grauda_VT_001

#include "Basic.hpp"

#include "BP_BubbleBox_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AIBubble_Grauda_VT_001.BP_AIBubble_Grauda_VT_001_C
// 0x0010 (0x0318 - 0x0308)
class ABP_AIBubble_Grauda_VT_001_C final : public ABP_BubbleBox_Base_C
{
public:
	class FText                                   HTAIbubble_Volume;                                 // 0x0308(0x0010)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AIBubble_Grauda_VT_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AIBubble_Grauda_VT_001_C")
	}
	static class ABP_AIBubble_Grauda_VT_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AIBubble_Grauda_VT_001_C>();
	}
};
DUMPER7_ASSERTS_ABP_AIBubble_Grauda_VT_001_C;

}

