#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CrowdShoot_Shoot

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CrowdShoot_Shoot.BP_CrowdShoot_Shoot_C
// 0x0010 (0x0048 - 0x0038)
class UBP_CrowdShoot_Shoot_C final : public UHTAnimNotify
{
public:
	TArray<TSubclassOf<class UGameplayEffect>>    Gameplay_Effect;                                   // 0x0038(0x0010)(Edit, BlueprintVisible)

public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CrowdShoot_Shoot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CrowdShoot_Shoot_C")
	}
	static class UBP_CrowdShoot_Shoot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CrowdShoot_Shoot_C>();
	}
};
DUMPER7_ASSERTS_UBP_CrowdShoot_Shoot_C;

}

