#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Idle_Cat_Lie_K110301

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Idle_Cat_Lie_K110301.BP_Idle_Cat_Lie_K110301_C
// 0x0000 (0x0360 - 0x0360)
class UBP_Idle_Cat_Lie_K110301_C final : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Idle_Cat_Lie_K110301_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Idle_Cat_Lie_K110301_C")
	}
	static class UBP_Idle_Cat_Lie_K110301_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Idle_Cat_Lie_K110301_C>();
	}
};
DUMPER7_ASSERTS_UBP_Idle_Cat_Lie_K110301_C;

}

