#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Npc_Animal_004

#include "Basic.hpp"

#include "BP_DialogueNPC_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Npc_Animal_004.BP_Npc_Animal_004_C
// 0x0000 (0x3180 - 0x3180)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_Npc_Animal_004_C : public ABP_DialogueNPC_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Npc_Animal_004_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Npc_Animal_004_C")
	}
	static class ABP_Npc_Animal_004_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Npc_Animal_004_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_ABP_Npc_Animal_004_C;

}

