#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_Sub_mlf

#include "Basic.hpp"

#include "BP_NPC_Sub_mlf_classes.hpp"
#include "BP_NPC_Sub_mlf_parameters.hpp"


namespace SDK
{

// Function BP_NPC_Sub_mlf.BP_NPC_Sub_mlf_C.ExecuteUbergraph_BP_NPC_Sub_mlf
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPC_Sub_mlf_C::ExecuteUbergraph_BP_NPC_Sub_mlf(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_Sub_mlf_C", "ExecuteUbergraph_BP_NPC_Sub_mlf");

	Params::BP_NPC_Sub_mlf_C_ExecuteUbergraph_BP_NPC_Sub_mlf Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPC_Sub_mlf.BP_NPC_Sub_mlf_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_NPC_Sub_mlf_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_Sub_mlf_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

