#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Npc_Animal_001

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Npc_Animal_001.BP_Npc_Animal_001_C
// 0x0010 (0x03E8 - 0x03D8)
class ABP_Npc_Animal_001_C : public AHTStylizationBirdActorPath
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        Arrow;                                             // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Npc_Animal_001(int32 EntryPoint);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Npc_Animal_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Npc_Animal_001_C")
	}
	static class ABP_Npc_Animal_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Npc_Animal_001_C>();
	}
};
DUMPER7_ASSERTS_ABP_Npc_Animal_001_C;

}

