#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_swimpool_aftertarget

#include "Basic.hpp"

#include "BP_swimpool_aftertarget_classes.hpp"
#include "BP_swimpool_aftertarget_parameters.hpp"


namespace SDK
{

// Function BP_swimpool_aftertarget.BP_swimpool_aftertarget_C.ExecuteUbergraph_BP_swimpool_aftertarget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_swimpool_aftertarget_C::ExecuteUbergraph_BP_swimpool_aftertarget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_swimpool_aftertarget_C", "ExecuteUbergraph_BP_swimpool_aftertarget");

	Params::BP_swimpool_aftertarget_C_ExecuteUbergraph_BP_swimpool_aftertarget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_swimpool_aftertarget.BP_swimpool_aftertarget_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_swimpool_aftertarget_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_swimpool_aftertarget_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

