#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Brid_Patrol_A

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_IdleState_FlyingPatrol_Route_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Brid_Patrol_A.Brid_Patrol_A_C
// 0x0010 (0x0430 - 0x0420)
#pragma pack(push, 0x1)
class alignas(0x10) UBrid_Patrol_A_C : public UBP_IdleState_FlyingPatrol_Route_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0420(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_Brid_Patrol_A(int32 EntryPoint);
	void BPOnEndState();
	void BPOnBeginState();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Brid_Patrol_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Brid_Patrol_A_C")
	}
	static class UBrid_Patrol_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBrid_Patrol_A_C>();
	}
};
#pragma pack(pop)
DUMPER7_ASSERTS_UBrid_Patrol_A_C;

}

