#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Boss07_SetHpStage04

#include "Basic.hpp"

#include "Buff_Boss07_SetHpStage01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_Boss07_SetHpStage04.Buff_Boss07_SetHpStage04_C
// 0x0000 (0x0C90 - 0x0C90)
class UBuff_Boss07_SetHpStage04_C final : public UBuff_Boss07_SetHpStage01_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_Boss07_SetHpStage04_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_Boss07_SetHpStage04_C")
	}
	static class UBuff_Boss07_SetHpStage04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuff_Boss07_SetHpStage04_C>();
	}
};
DUMPER7_ASSERTS_UBuff_Boss07_SetHpStage04_C;

}

