#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_KuharaSkill3_Hit

#include "Basic.hpp"

#include "BP_CameraShake_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CameraShake_KuharaSkill3_Hit.CameraShake_KuharaSkill3_Hit_C
// 0x0000 (0x01F0 - 0x01F0)
class UCameraShake_KuharaSkill3_Hit_C final : public UBP_CameraShake_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_KuharaSkill3_Hit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_KuharaSkill3_Hit_C")
	}
	static class UCameraShake_KuharaSkill3_Hit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_KuharaSkill3_Hit_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_KuharaSkill3_Hit_C;

}

