#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Jin_QTE

#include "Basic.hpp"

#include "GA_QTEBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Jin_QTE.GA_Jin_QTE_C
// 0x0000 (0x0BD0 - 0x0BD0)
class UGA_Jin_QTE_C final : public UGA_QTEBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Jin_QTE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Jin_QTE_C")
	}
	static class UGA_Jin_QTE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Jin_QTE_C>();
	}
};
DUMPER7_ASSERTS_UGA_Jin_QTE_C;

}

