#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JinMelee6Float

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass JinMelee6Float.JinMelee6Float_C
// 0x0000 (0x01F8 - 0x01F8)
class UJinMelee6Float_C final : public UHTSkillEffect_HitFloating
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("JinMelee6Float_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"JinMelee6Float_C")
	}
	static class UJinMelee6Float_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJinMelee6Float_C>();
	}
};
DUMPER7_ASSERTS_UJinMelee6Float_C;

}

