#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mass_SO_Photo

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mass_SO_Photo.Mass_SO_Photo_C
// 0x0000 (0x0B88 - 0x0B88)
class AMass_SO_Photo_C final : public AHTSmartObjectActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Mass_SO_Photo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Mass_SO_Photo_C")
	}
	static class AMass_SO_Photo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMass_SO_Photo_C>();
	}
};
DUMPER7_ASSERTS_AMass_SO_Photo_C;

}

