#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mon_38_IdleStates_Pose_Yawn

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mon_38_IdleStates_Pose_Yawn.Mon_38_IdleStates_Pose_Yawn_C
// 0x0000 (0x0360 - 0x0360)
class UMon_38_IdleStates_Pose_Yawn_C final : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Mon_38_IdleStates_Pose_Yawn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Mon_38_IdleStates_Pose_Yawn_C")
	}
	static class UMon_38_IdleStates_Pose_Yawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMon_38_IdleStates_Pose_Yawn_C>();
	}
};
DUMPER7_ASSERTS_UMon_38_IdleStates_Pose_Yawn_C;

}

