#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: mon_012_2_BP

#include "Basic.hpp"

#include "mon_012_2_BP_classes.hpp"
#include "mon_012_2_BP_parameters.hpp"


namespace SDK
{

// Function mon_012_2_BP.mon_012_2_BP_C.Act08_Check
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::Act08_Check()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "Act08_Check");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.act08check_end
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::act08check_end()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "act08check_end");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.act10_rotation_1
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::act10_rotation_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "act10_rotation_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.act10_rotation_2
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::act10_rotation_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "act10_rotation_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.BndEvt__mon_012_2_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void Amon_012_2_BP_C::BndEvt__mon_012_2_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "BndEvt__mon_012_2_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature");

	Params::mon_012_2_BP_C_BndEvt__mon_012_2_BP_Box_K2Node_ComponentBoundEvent_4_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_012_2_BP.mon_012_2_BP_C.bodyhide
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::bodyhide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "bodyhide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.bodyopen
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::bodyopen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "bodyopen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.BPOnAICharacterDead
// (Event, Public, BlueprintEvent)

void Amon_012_2_BP_C::BPOnAICharacterDead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "BPOnAICharacterDead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.BPOnLeaveBattleBegin
// (Event, Public, BlueprintEvent)

void Amon_012_2_BP_C::BPOnLeaveBattleBegin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "BPOnLeaveBattleBegin");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.BPOnLeaveBattleEnd
// (Event, Public, BlueprintEvent)

void Amon_012_2_BP_C::BPOnLeaveBattleEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "BPOnLeaveBattleEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.CheckCheck
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::CheckCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "CheckCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.Dead_FX
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::Dead_FX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "Dead_FX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.ExecuteUbergraph_mon_012_2_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_012_2_BP_C::ExecuteUbergraph_mon_012_2_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "ExecuteUbergraph_mon_012_2_BP");

	Params::mon_012_2_BP_C_ExecuteUbergraph_mon_012_2_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_012_2_BP.mon_012_2_BP_C.IntoBattle_FX
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::IntoBattle_FX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "IntoBattle_FX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.IntoWallCheck
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::IntoWallCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "IntoWallCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.NewFunction
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SocketName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         Return_LOC                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_012_2_BP_C::NewFunction(class FName SocketName, struct FVector* Return_LOC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "NewFunction");

	Params::mon_012_2_BP_C_NewFunction Parms{};

	Parms.SocketName = SocketName;

	UObject::ProcessEvent(Func, &Parms);

	if (Return_LOC != nullptr)
		*Return_LOC = std::move(Parms.Return_LOC);
}


// Function mon_012_2_BP.mon_012_2_BP_C.Really_Open_Body
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::Really_Open_Body()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "Really_Open_Body");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Amon_012_2_BP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.Target_Where
// (BlueprintCallable, BlueprintEvent)

void Amon_012_2_BP_C::Target_Where()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "Target_Where");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_0__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_0__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_1__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_1__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_2__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_2__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_2__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_2__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_2__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_2__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_3__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_3__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_3__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_3__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_3__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_3__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_4__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_4__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_4__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_4__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_4__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_4__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_5__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_5__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_5__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_5__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_5__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_5__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_6__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_6__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_6__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴_6__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴_6__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴_6__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴__FinishedFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_012_2_BP.mon_012_2_BP_C.时间轴__UpdateFunc
// (BlueprintEvent)

void Amon_012_2_BP_C::时间轴__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_012_2_BP_C", "时间轴__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

