#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: paperairplane_Perform

#include "Basic.hpp"

#include "paperairplane_Perform_classes.hpp"
#include "paperairplane_Perform_parameters.hpp"


namespace SDK
{

// Function paperairplane_Perform.paperairplane_Perform_C.BndEvt__paperairplane_Perform_Perform_range_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void Apaperairplane_Perform_C::BndEvt__paperairplane_Perform_Perform_range_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "BndEvt__paperairplane_Perform_Perform_range_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::paperairplane_Perform_C_BndEvt__paperairplane_Perform_Perform_range_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.BPInteractFinishEffect
// (Event, Public, BlueprintEvent)
// Parameters:
// class AHTPlayerController*              ByPC                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   InteractIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::BPInteractFinishEffect(class AHTPlayerController* ByPC, int32 InteractIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "BPInteractFinishEffect");

	Params::paperairplane_Perform_C_BPInteractFinishEffect Parms{};

	Parms.ByPC = ByPC;
	Parms.InteractIndex = InteractIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Check Weather to Spawn
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Check_Weather_to_Spawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Check Weather to Spawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.ExecuteUbergraph_paperairplane_Perform
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::ExecuteUbergraph_paperairplane_Perform(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "ExecuteUbergraph_paperairplane_Perform");

	Params::paperairplane_Perform_C_ExecuteUbergraph_paperairplane_Perform Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Interact when Rain
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Interact_when_Rain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Interact when Rain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Leave_battle
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Leave_battle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Leave_battle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnFail_03814E474FC24FA6D6B059B1A58F4840
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnFail_03814E474FC24FA6D6B059B1A58F4840(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnFail_03814E474FC24FA6D6B059B1A58F4840");

	Params::paperairplane_Perform_C_OnFail_03814E474FC24FA6D6B059B1A58F4840 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnFail_12E86E804C5BCAD33410BEA2B4BC7410
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnFail_12E86E804C5BCAD33410BEA2B4BC7410(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnFail_12E86E804C5BCAD33410BEA2B4BC7410");

	Params::paperairplane_Perform_C_OnFail_12E86E804C5BCAD33410BEA2B4BC7410 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnFail_7BF42BE94DB8C55FDCF833B29E4B6C4B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnFail_7BF42BE94DB8C55FDCF833B29E4B6C4B(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnFail_7BF42BE94DB8C55FDCF833B29E4B6C4B");

	Params::paperairplane_Perform_C_OnFail_7BF42BE94DB8C55FDCF833B29E4B6C4B Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnFail_CF2671B4405DF30DBAFF738423C24328
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnFail_CF2671B4405DF30DBAFF738423C24328(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnFail_CF2671B4405DF30DBAFF738423C24328");

	Params::paperairplane_Perform_C_OnFail_CF2671B4405DF30DBAFF738423C24328 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnFail_DF4CF84A4BD53D293836D8BBDD4CC374
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnFail_DF4CF84A4BD53D293836D8BBDD4CC374(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnFail_DF4CF84A4BD53D293836D8BBDD4CC374");

	Params::paperairplane_Perform_C_OnFail_DF4CF84A4BD53D293836D8BBDD4CC374 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnLoaded_F6DDFC9D4FBB8A6BABBA3CBA1F64F034
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnLoaded_F6DDFC9D4FBB8A6BABBA3CBA1F64F034(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnLoaded_F6DDFC9D4FBB8A6BABBA3CBA1F64F034");

	Params::paperairplane_Perform_C_OnLoaded_F6DDFC9D4FBB8A6BABBA3CBA1F64F034 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnSuccess_03814E474FC24FA6D6B059B1A58F4840
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnSuccess_03814E474FC24FA6D6B059B1A58F4840(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnSuccess_03814E474FC24FA6D6B059B1A58F4840");

	Params::paperairplane_Perform_C_OnSuccess_03814E474FC24FA6D6B059B1A58F4840 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnSuccess_12E86E804C5BCAD33410BEA2B4BC7410
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnSuccess_12E86E804C5BCAD33410BEA2B4BC7410(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnSuccess_12E86E804C5BCAD33410BEA2B4BC7410");

	Params::paperairplane_Perform_C_OnSuccess_12E86E804C5BCAD33410BEA2B4BC7410 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnSuccess_7BF42BE94DB8C55FDCF833B29E4B6C4B
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnSuccess_7BF42BE94DB8C55FDCF833B29E4B6C4B(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnSuccess_7BF42BE94DB8C55FDCF833B29E4B6C4B");

	Params::paperairplane_Perform_C_OnSuccess_7BF42BE94DB8C55FDCF833B29E4B6C4B Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnSuccess_CF2671B4405DF30DBAFF738423C24328
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnSuccess_CF2671B4405DF30DBAFF738423C24328(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnSuccess_CF2671B4405DF30DBAFF738423C24328");

	Params::paperairplane_Perform_C_OnSuccess_CF2671B4405DF30DBAFF738423C24328 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.OnSuccess_DF4CF84A4BD53D293836D8BBDD4CC374
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTAISpawnManager*                Spawn_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::OnSuccess_DF4CF84A4BD53D293836D8BBDD4CC374(class AHTAISpawnManager* Spawn_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "OnSuccess_DF4CF84A4BD53D293836D8BBDD4CC374");

	Params::paperairplane_Perform_C_OnSuccess_DF4CF84A4BD53D293836D8BBDD4CC374 Parms{};

	Parms.Spawn_0 = Spawn_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function paperairplane_Perform.paperairplane_Perform_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Apaperairplane_Perform_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Reset Perform Range
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Reset_Perform_Range()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Reset Perform Range");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Reset Rain
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Reset_Rain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Reset Rain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Reset Sunny
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Reset_Sunny()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Reset Sunny");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Spawn when Sunny
// (BlueprintCallable, BlueprintEvent)

void Apaperairplane_Perform_C::Spawn_when_Sunny()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Spawn when Sunny");

	UObject::ProcessEvent(Func, nullptr);
}


// Function paperairplane_Perform.paperairplane_Perform_C.Weather Change Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UHottaPrimaryDataAsset*           HottaPrimaryDataAsset                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void Apaperairplane_Perform_C::Weather_Change_Event(class UHottaPrimaryDataAsset* HottaPrimaryDataAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("paperairplane_Perform_C", "Weather Change Event");

	Params::paperairplane_Perform_C_Weather_Change_Event Parms{};

	Parms.HottaPrimaryDataAsset = HottaPrimaryDataAsset;

	UObject::ProcessEvent(Func, &Parms);
}

}

