#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: player_055_kuhara

#include "Basic.hpp"

#include "player_055_kuhara_classes.hpp"
#include "player_055_kuhara_parameters.hpp"


namespace SDK
{

// Function player_055_kuhara.player_055_kuhara_C.ExecuteUbergraph_player_055_kuhara
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aplayer_055_kuhara_C::ExecuteUbergraph_player_055_kuhara(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_055_kuhara_C", "ExecuteUbergraph_player_055_kuhara");

	Params::player_055_kuhara_C_ExecuteUbergraph_player_055_kuhara Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function player_055_kuhara.player_055_kuhara_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Aplayer_055_kuhara_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("player_055_kuhara_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

