#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropBox_Geft_H_Area01_001

#include "Basic.hpp"

#include "PropBox_Geft_A_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PropBox_Geft_H_Area01_001.PropBox_Geft_H_Area01_001_C
// 0x0000 (0x0EC0 - 0x0EC0)
class APropBox_Geft_H_Area01_001_C final : public APropBox_Geft_A_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PropBox_Geft_H_Area01_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PropBox_Geft_H_Area01_001_C")
	}
	static class APropBox_Geft_H_Area01_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APropBox_Geft_H_Area01_001_C>();
	}
};
DUMPER7_ASSERTS_APropBox_Geft_H_Area01_001_C;

}

