#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PropBox_Base_Once

#include "Basic.hpp"

#include "PropBox_Base_Once_classes.hpp"
#include "PropBox_Base_Once_parameters.hpp"


namespace SDK
{

// Function PropBox_Base_Once.PropBox_Base_Once_C.ExecuteUbergraph_PropBox_Base_Once
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APropBox_Base_Once_C::ExecuteUbergraph_PropBox_Base_Once(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PropBox_Base_Once_C", "ExecuteUbergraph_PropBox_Base_Once");

	Params::PropBox_Base_Once_C_ExecuteUbergraph_PropBox_Base_Once Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PropBox_Base_Once.PropBox_Base_Once_C.BP_OnOpen
// (Event, Public, BlueprintEvent)

void APropBox_Base_Once_C::BP_OnOpen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PropBox_Base_Once_C", "BP_OnOpen");

	UObject::ProcessEvent(Func, nullptr);
}

}

