#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SFVA_0004

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SFVA_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SFVA_0004.SFVA_0004_C
// 0x0020 (0x0C60 - 0x0C40)
class ASFVA_0004_C final : public ASFVA_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_SFVA_0004_C;                        // 0x0C40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USphereComponent*                       Sphere2;                                           // 0x0C48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x0C50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0C58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SFVA_0004(int32 EntryPoint);
	void OnFurnitureInteracted();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SFVA_0004_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SFVA_0004_C")
	}
	static class ASFVA_0004_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASFVA_0004_C>();
	}
};
DUMPER7_ASSERTS_ASFVA_0004_C;

}

