#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShopStealGoods_DSDt_001

#include "Basic.hpp"

#include "ShopStealGoods_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShopStealGoods_DSDt_001.ShopStealGoods_DSDt_001_C
// 0x0000 (0x0C68 - 0x0C68)
class AShopStealGoods_DSDt_001_C final : public AShopStealGoods_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ShopStealGoods_DSDt_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ShopStealGoods_DSDt_001_C")
	}
	static class AShopStealGoods_DSDt_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AShopStealGoods_DSDt_001_C>();
	}
};
DUMPER7_ASSERTS_AShopStealGoods_DSDt_001_C;

}

