#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tayge_Animation_q110191

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tayge_Animation_q110191.Tayge_Animation_q110191_C
// 0x0000 (0x0360 - 0x0360)
class UTayge_Animation_q110191_C final : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Tayge_Animation_q110191_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Tayge_Animation_q110191_C")
	}
	static class UTayge_Animation_q110191_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTayge_Animation_q110191_C>();
	}
};
DUMPER7_ASSERTS_UTayge_Animation_q110191_C;

}

