#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Anomaly_085

#include "Basic.hpp"

#include "Anomaly_085_classes.hpp"
#include "Anomaly_085_parameters.hpp"


namespace SDK
{

// Function Anomaly_085.Anomaly_085_C.BndEvt__Anomaly_085_Follow Trigger_K2Node_ComponentBoundEvent_2_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAnomaly_085_C::BndEvt__Anomaly_085_Follow_Trigger_K2Node_ComponentBoundEvent_2_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "BndEvt__Anomaly_085_Follow Trigger_K2Node_ComponentBoundEvent_2_ComponentEndOverlapSignature__DelegateSignature");

	Params::Anomaly_085_C_BndEvt__Anomaly_085_Follow_Trigger_K2Node_ComponentBoundEvent_2_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Anomaly_085.Anomaly_085_C.BPOnTakeDamage
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   DamageAmount                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FDamageEvent&              DamageEvent                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class AController*                      EventInstigator                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AAnomaly_085_C::BPOnTakeDamage(float DamageAmount, const struct FDamageEvent& DamageEvent, class AController* EventInstigator, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "BPOnTakeDamage");

	Params::Anomaly_085_C_BPOnTakeDamage Parms{};

	Parms.DamageAmount = DamageAmount;
	Parms.DamageEvent = std::move(DamageEvent);
	Parms.EventInstigator = EventInstigator;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Anomaly_085.Anomaly_085_C.ExecuteUbergraph_Anomaly_085
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAnomaly_085_C::ExecuteUbergraph_Anomaly_085(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "ExecuteUbergraph_Anomaly_085");

	Params::Anomaly_085_C_ExecuteUbergraph_Anomaly_085 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Anomaly_085.Anomaly_085_C.Floating__FinishedFunc
// (BlueprintEvent)

void AAnomaly_085_C::Floating__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "Floating__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Anomaly_085.Anomaly_085_C.Floating__UpdateFunc
// (BlueprintEvent)

void AAnomaly_085_C::Floating__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "Floating__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Anomaly_085.Anomaly_085_C.Follow Begin__FinishedFunc
// (BlueprintEvent)

void AAnomaly_085_C::Follow_Begin__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "Follow Begin__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Anomaly_085.Anomaly_085_C.Follow Begin__UpdateFunc
// (BlueprintEvent)

void AAnomaly_085_C::Follow_Begin__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "Follow Begin__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Anomaly_085.Anomaly_085_C.Follow Player
// (BlueprintCallable, BlueprintEvent)

void AAnomaly_085_C::Follow_Player()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "Follow Player");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Anomaly_085.Anomaly_085_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAnomaly_085_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Anomaly_085.Anomaly_085_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAnomaly_085_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "ReceiveTick");

	Params::Anomaly_085_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Anomaly_085.Anomaly_085_C.Umbrella Floating
// (BlueprintCallable, BlueprintEvent)

void AAnomaly_085_C::Umbrella_Floating()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Anomaly_085_C", "Umbrella Floating");

	UObject::ProcessEvent(Func, nullptr);
}

}

