#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CityEvent_LevelManager_SH_001

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CityEvent_LevelInstanceManager_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CityEvent_LevelManager_SH_001.BP_CityEvent_LevelManager_SH_001_C
// 0x0008 (0x03E8 - 0x03E0)
class ABP_CityEvent_LevelManager_SH_001_C final : public ABP_CityEvent_LevelInstanceManager_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CityEvent_LevelManager_SH_001_C; // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_OnLevelEvent(const class FName& InEventID);
	void ExecuteUbergraph_BP_CityEvent_LevelManager_SH_001(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CityEvent_LevelManager_SH_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CityEvent_LevelManager_SH_001_C")
	}
	static class ABP_CityEvent_LevelManager_SH_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CityEvent_LevelManager_SH_001_C>();
	}
};
DUMPER7_ASSERTS_ABP_CityEvent_LevelManager_SH_001_C;

}

