#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExpandingFieldActor

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ExpandingFieldActor.BP_ExpandingFieldActor_C
// 0x0000 (0x0550 - 0x0550)
class ABP_ExpandingFieldActor_C : public AHTExpandingField
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExpandingFieldActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExpandingFieldActor_C")
	}
	static class ABP_ExpandingFieldActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ExpandingFieldActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_ExpandingFieldActor_C;

}

