#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FurnitureActorBase_0016

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_FurnitureActorBase_0016.BP_FurnitureActorBase_0016_C.ExecuteUbergraph_BP_FurnitureActorBase_0016
// 0x0004 (0x0004 - 0x0000)
struct BP_FurnitureActorBase_0016_C_ExecuteUbergraph_BP_FurnitureActorBase_0016 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FurnitureActorBase_0016_C_ExecuteUbergraph_BP_FurnitureActorBase_0016;

}

