#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FishTank_04

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FishTank_04.BP_FishTank_04_C
// 0x0020 (0x02E8 - 0x02C8)
class ABP_FishTank_04_C final : public AActor
{
public:
	class UNiagaraComponent*                      NS_FishShop_Bubbles_002;                           // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_Fish_005;                                       // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_FishTank_04;                                    // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FishTank_04_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FishTank_04_C")
	}
	static class ABP_FishTank_04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FishTank_04_C>();
	}
};
DUMPER7_ASSERTS_ABP_FishTank_04_C;

}

