#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HTAIMovePoint_mon_34_Patrol

#include "Basic.hpp"

#include "BP_HTAIMovePoint_mon_34_Patrol_classes.hpp"
#include "BP_HTAIMovePoint_mon_34_Patrol_parameters.hpp"


namespace SDK
{

// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.BndEvt__BP_HTAIMovePoint_mon_34_LostFound_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_HTAIMovePoint_mon_34_Patrol_C::BndEvt__BP_HTAIMovePoint_mon_34_LostFound_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "BndEvt__BP_HTAIMovePoint_mon_34_LostFound_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_BndEvt__BP_HTAIMovePoint_mon_34_LostFound_Sphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.ExecuteUbergraph_BP_HTAIMovePoint_mon_34_Patrol
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HTAIMovePoint_mon_34_Patrol_C::ExecuteUbergraph_BP_HTAIMovePoint_mon_34_Patrol(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "ExecuteUbergraph_BP_HTAIMovePoint_mon_34_Patrol");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_ExecuteUbergraph_BP_HTAIMovePoint_mon_34_Patrol Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.OnBlendOut_EE60A6F649B2277E1A2AD79C32C1D29F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HTAIMovePoint_mon_34_Patrol_C::OnBlendOut_EE60A6F649B2277E1A2AD79C32C1D29F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "OnBlendOut_EE60A6F649B2277E1A2AD79C32C1D29F");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_OnBlendOut_EE60A6F649B2277E1A2AD79C32C1D29F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.OnCompleted_EE60A6F649B2277E1A2AD79C32C1D29F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HTAIMovePoint_mon_34_Patrol_C::OnCompleted_EE60A6F649B2277E1A2AD79C32C1D29F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "OnCompleted_EE60A6F649B2277E1A2AD79C32C1D29F");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_OnCompleted_EE60A6F649B2277E1A2AD79C32C1D29F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.OnInterrupted_EE60A6F649B2277E1A2AD79C32C1D29F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HTAIMovePoint_mon_34_Patrol_C::OnInterrupted_EE60A6F649B2277E1A2AD79C32C1D29F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "OnInterrupted_EE60A6F649B2277E1A2AD79C32C1D29F");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_OnInterrupted_EE60A6F649B2277E1A2AD79C32C1D29F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.OnNotifyBegin_EE60A6F649B2277E1A2AD79C32C1D29F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HTAIMovePoint_mon_34_Patrol_C::OnNotifyBegin_EE60A6F649B2277E1A2AD79C32C1D29F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "OnNotifyBegin_EE60A6F649B2277E1A2AD79C32C1D29F");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_OnNotifyBegin_EE60A6F649B2277E1A2AD79C32C1D29F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HTAIMovePoint_mon_34_Patrol.BP_HTAIMovePoint_mon_34_Patrol_C.OnNotifyEnd_EE60A6F649B2277E1A2AD79C32C1D29F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HTAIMovePoint_mon_34_Patrol_C::OnNotifyEnd_EE60A6F649B2277E1A2AD79C32C1D29F(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HTAIMovePoint_mon_34_Patrol_C", "OnNotifyEnd_EE60A6F649B2277E1A2AD79C32C1D29F");

	Params::BP_HTAIMovePoint_mon_34_Patrol_C_OnNotifyEnd_EE60A6F649B2277E1A2AD79C32C1D29F Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}

}

