#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HospitalEntrance

#include "Basic.hpp"

#include "BP_HospitalEntrance_classes.hpp"
#include "BP_HospitalEntrance_parameters.hpp"


namespace SDK
{

// Function BP_HospitalEntrance.BP_HospitalEntrance_C.BndEvt__BP_HospitalEntrance_HTDialogue_K2Node_ComponentBoundEvent_0_OnDialogueEventDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FName                             InParticipant                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             InEventName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HospitalEntrance_C::BndEvt__BP_HospitalEntrance_HTDialogue_K2Node_ComponentBoundEvent_0_OnDialogueEventDelegate__DelegateSignature(class FName InParticipant, class FName InEventName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HospitalEntrance_C", "BndEvt__BP_HospitalEntrance_HTDialogue_K2Node_ComponentBoundEvent_0_OnDialogueEventDelegate__DelegateSignature");

	Params::BP_HospitalEntrance_C_BndEvt__BP_HospitalEntrance_HTDialogue_K2Node_ComponentBoundEvent_0_OnDialogueEventDelegate__DelegateSignature Parms{};

	Parms.InParticipant = InParticipant;
	Parms.InEventName = InEventName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HospitalEntrance.BP_HospitalEntrance_C.BPGetInteractEntries
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AHTPlayerController*              ByPC                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FInteractEntry>*          OutInteractEntries                                     (Parm, OutParm, ContainsInstancedReference)

void ABP_HospitalEntrance_C::BPGetInteractEntries(class AHTPlayerController* ByPC, TArray<struct FInteractEntry>* OutInteractEntries)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HospitalEntrance_C", "BPGetInteractEntries");

	Params::BP_HospitalEntrance_C_BPGetInteractEntries Parms{};

	Parms.ByPC = ByPC;

	UObject::ProcessEvent(Func, &Parms);

	if (OutInteractEntries != nullptr)
		*OutInteractEntries = std::move(Parms.OutInteractEntries);
}


// Function BP_HospitalEntrance.BP_HospitalEntrance_C.BPOnMainRoleLoadFinished
// (Event, Public, BlueprintEvent)
// Parameters:
// class AHTPlayerState*                   PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_HospitalEntrance_C::BPOnMainRoleLoadFinished(class AHTPlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HospitalEntrance_C", "BPOnMainRoleLoadFinished");

	Params::BP_HospitalEntrance_C_BPOnMainRoleLoadFinished Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HospitalEntrance.BP_HospitalEntrance_C.Completed_4B8FE0B1404ED3A047004FA60ACE9FAB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         WidgetObject                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_HospitalEntrance_C::Completed_4B8FE0B1404ED3A047004FA60ACE9FAB(class UCommonActivatableWidget* WidgetObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HospitalEntrance_C", "Completed_4B8FE0B1404ED3A047004FA60ACE9FAB");

	Params::BP_HospitalEntrance_C_Completed_4B8FE0B1404ED3A047004FA60ACE9FAB Parms{};

	Parms.WidgetObject = WidgetObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HospitalEntrance.BP_HospitalEntrance_C.Completed_CE4964B54F33B693DE06AEA4F2CFAF31
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatableWidget*         WidgetObject                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_HospitalEntrance_C::Completed_CE4964B54F33B693DE06AEA4F2CFAF31(class UCommonActivatableWidget* WidgetObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HospitalEntrance_C", "Completed_CE4964B54F33B693DE06AEA4F2CFAF31");

	Params::BP_HospitalEntrance_C_Completed_CE4964B54F33B693DE06AEA4F2CFAF31 Parms{};

	Parms.WidgetObject = WidgetObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HospitalEntrance.BP_HospitalEntrance_C.ExecuteUbergraph_BP_HospitalEntrance
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HospitalEntrance_C::ExecuteUbergraph_BP_HospitalEntrance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HospitalEntrance_C", "ExecuteUbergraph_BP_HospitalEntrance");

	Params::BP_HospitalEntrance_C_ExecuteUbergraph_BP_HospitalEntrance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

