#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_06906

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_NPC_069_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_06906.BP_NPC_06906_C
// 0x0020 (0x3300 - 0x32E0)
class ABP_NPC_06906_C final : public ABP_NPC_069_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x32E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCameraComponent*                       Camera;                                            // 0x32E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpringArmComponent*                    SpringArm;                                         // 0x32F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FName                                   In_Event_Name;                                     // 0x32F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_NPC_06906(int32 EntryPoint);
	void BndEvt__BP_NPC_06906_HTDialogue_K2Node_ComponentBoundEvent_0_OnDialogueEventDelegate__DelegateSignature(class FName InParticipant, class FName InEventName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_06906_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_06906_C")
	}
	static class ABP_NPC_06906_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_06906_C>();
	}
};
DUMPER7_ASSERTS_ABP_NPC_06906_C;

}

