#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ParkingGate_Exit

#include "Basic.hpp"

#include "BP_ParkingGate_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ParkingGate_Exit.BP_ParkingGate_Exit_C
// 0x0000 (0x0BE8 - 0x0BE8)
class ABP_ParkingGate_Exit_C final : public ABP_ParkingGate_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ParkingGate_Exit_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ParkingGate_Exit_C")
	}
	static class ABP_ParkingGate_Exit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ParkingGate_Exit_C>();
	}
};
DUMPER7_ASSERTS_ABP_ParkingGate_Exit_C;

}

