#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TrainStationAudio

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TrainStationAudio.BP_TrainStationAudio_C
// 0x0008 (0x0C18 - 0x0C10)
class ABP_TrainStationAudio_C final : public AHTTrainTrafficStationAudioActor
{
public:
	class UBillboardComponent*                    Billboard;                                         // 0x0C10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TrainStationAudio_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TrainStationAudio_C")
	}
	static class ABP_TrainStationAudio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TrainStationAudio_C>();
	}
};
DUMPER7_ASSERTS_ABP_TrainStationAudio_C;

}

