#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIItemTips

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_UIItemTips.BP_UIItemTips_C
// 0x0018 (0x0F28 - 0x0F10)
class UBP_UIItemTips_C final : public UHTUI_ItemTips
{
public:
	class UWB_GamepadKeysTips_C*                  WB_GamepadKeysTips;                                // 0x0F10(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Bg;                                          // 0x0F18(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBoundActionBar*                  CommonBoundActionBar_274;                          // 0x0F20(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UIItemTips_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UIItemTips_C")
	}
	static class UBP_UIItemTips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UIItemTips_C>();
	}
};
DUMPER7_ASSERTS_UBP_UIItemTips_C;

}

