#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPCharacterActor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPCharacterActor.BPCharacterActor_C
// 0x0018 (0x0460 - 0x0448)
class ABPCharacterActor_C final : public AHTCharacterActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0448(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UHTNiagaraComponent*                    HTNiagara;                                         // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UHTNiagaraComponent*                    ForkNiagara;                                       // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPCharacterActor(int32 EntryPoint);
	void BP_ShowForkEffect(bool bShow, bool IsEmpty);
	void BP_ActivatedPowerEffect(bool bActivate);

	class UWidgetComponent* GetFormationMemberWC() const;
	class UHTNiagaraComponent* GetForkNiagara() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPCharacterActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPCharacterActor_C")
	}
	static class ABPCharacterActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPCharacterActor_C>();
	}
};
DUMPER7_ASSERTS_ABPCharacterActor_C;

}

