#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_AuctionShopMain

#include "Basic.hpp"

#include "BPUI_AuctionShopMain_classes.hpp"
#include "BPUI_AuctionShopMain_parameters.hpp"


namespace SDK
{

// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.SequenceEvent__ENTRYPOINTBPUI_AuctionShopMain_0
// (Public, BlueprintCallable, BlueprintEvent)

void UBPUI_AuctionShopMain_C::SequenceEvent__ENTRYPOINTBPUI_AuctionShopMain_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "SequenceEvent__ENTRYPOINTBPUI_AuctionShopMain_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.SequenceEvent__ENTRYPOINTBPUI_AuctionShopMain
// (Public, BlueprintCallable, BlueprintEvent)

void UBPUI_AuctionShopMain_C::SequenceEvent__ENTRYPOINTBPUI_AuctionShopMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "SequenceEvent__ENTRYPOINTBPUI_AuctionShopMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.SequenceEvent_0
// (BlueprintCallable, BlueprintEvent)

void UBPUI_AuctionShopMain_C::SequenceEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "SequenceEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.SequenceEvent
// (BlueprintCallable, BlueprintEvent)

void UBPUI_AuctionShopMain_C::SequenceEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "SequenceEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.ExecuteUbergraph_BPUI_AuctionShopMain
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPUI_AuctionShopMain_C::ExecuteUbergraph_BPUI_AuctionShopMain(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "ExecuteUbergraph_BPUI_AuctionShopMain");

	Params::BPUI_AuctionShopMain_C_ExecuteUbergraph_BPUI_AuctionShopMain Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_AuctionShopMain_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPUI_AuctionShopMain.BPUI_AuctionShopMain_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBPUI_AuctionShopMain_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPUI_AuctionShopMain_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

