#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_ForkAttributeTipsSlot

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPUI_ForkAttributeTipsSlot.BPUI_ForkAttributeTipsSlot_C.ExecuteUbergraph_BPUI_ForkAttributeTipsSlot
// 0x0004 (0x0004 - 0x0000)
struct BPUI_ForkAttributeTipsSlot_C_ExecuteUbergraph_BPUI_ForkAttributeTipsSlot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_ForkAttributeTipsSlot_C_ExecuteUbergraph_BPUI_ForkAttributeTipsSlot;

}

