#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_CommonBG2

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPUI_CommonBG2.BPUI_CommonBG2_C
// 0x0010 (0x0EE0 - 0x0ED0)
class UBPUI_CommonBG2_C final : public UHTUIBase
{
public:
	class UImage*                                 Image_Bg_Huawen01;                                 // 0x0ED0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Bg;                                          // 0x0ED8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_CloseAnim();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPUI_CommonBG2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPUI_CommonBG2_C")
	}
	static class UBPUI_CommonBG2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_CommonBG2_C>();
	}
};
DUMPER7_ASSERTS_UBPUI_CommonBG2_C;

}

