#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_CombatAwardExpInfo

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPUI_CombatAwardExpInfo.BPUI_CombatAwardExpInfo_C.ExecuteUbergraph_BPUI_CombatAwardExpInfo
// 0x000C (0x000C - 0x0000)
struct BPUI_CombatAwardExpInfo_C_ExecuteUbergraph_BPUI_CombatAwardExpInfo final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEventGlobal_ReturnValue;              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEventGlobal_ReturnValue_1;            // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_CombatAwardExpInfo_C_ExecuteUbergraph_BPUI_CombatAwardExpInfo;

}

