#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: buff_mon_013_steal_Immune

#include "Basic.hpp"

#include "BuffBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass buff_mon_013_steal_Immune.buff_mon_013_steal_Immune_C
// 0x0000 (0x0C90 - 0x0C90)
class Ubuff_mon_013_steal_Immune_C final : public UBuffBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("buff_mon_013_steal_Immune_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"buff_mon_013_steal_Immune_C")
	}
	static class Ubuff_mon_013_steal_Immune_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ubuff_mon_013_steal_Immune_C>();
	}
};
DUMPER7_ASSERTS_Ubuff_mon_013_steal_Immune_C;

}

