#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageActorHanielUltraSkill1

#include "Basic.hpp"

#include "DamageActorHanielUltraSkill1_classes.hpp"
#include "DamageActorHanielUltraSkill1_parameters.hpp"


namespace SDK
{

// Function DamageActorHanielUltraSkill1.DamageActorHanielUltraSkill1_C.ExecuteUbergraph_DamageActorHanielUltraSkill1
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADamageActorHanielUltraSkill1_C::ExecuteUbergraph_DamageActorHanielUltraSkill1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DamageActorHanielUltraSkill1_C", "ExecuteUbergraph_DamageActorHanielUltraSkill1");

	Params::DamageActorHanielUltraSkill1_C_ExecuteUbergraph_DamageActorHanielUltraSkill1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DamageActorHanielUltraSkill1.DamageActorHanielUltraSkill1_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADamageActorHanielUltraSkill1_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DamageActorHanielUltraSkill1_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

