#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_mon_12_act10_1_BP

#include "Basic.hpp"

#include "GA_mon_12_act10_1_BP_classes.hpp"
#include "GA_mon_12_act10_1_BP_parameters.hpp"


namespace SDK
{

// Function GA_mon_12_act10_1_BP.GA_mon_12_act10_1_BP_C.EventReceived_8ADAF3F24F81733D645DADBD060EAFA2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_mon_12_act10_1_BP_C::EventReceived_8ADAF3F24F81733D645DADBD060EAFA2(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_mon_12_act10_1_BP_C", "EventReceived_8ADAF3F24F81733D645DADBD060EAFA2");

	Params::GA_mon_12_act10_1_BP_C_EventReceived_8ADAF3F24F81733D645DADBD060EAFA2 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_mon_12_act10_1_BP.GA_mon_12_act10_1_BP_C.ExecuteUbergraph_GA_mon_12_act10_1_BP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_mon_12_act10_1_BP_C::ExecuteUbergraph_GA_mon_12_act10_1_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_mon_12_act10_1_BP_C", "ExecuteUbergraph_GA_mon_12_act10_1_BP");

	Params::GA_mon_12_act10_1_BP_C_ExecuteUbergraph_GA_mon_12_act10_1_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_mon_12_act10_1_BP.GA_mon_12_act10_1_BP_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_mon_12_act10_1_BP_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_mon_12_act10_1_BP_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}

}

