#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Liyuuqi

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Liyuuqi.Liyuuqi
// NumValues: 0x0008
enum class ELiyuuqi : uint8
{
	NewEnumerator5                           = 0,
	NewEnumerator6                           = 1,
	NewEnumerator7                           = 2,
	NewEnumerator8                           = 3,
	NewEnumerator9                           = 4,
	NewEnumerator10                          = 5,
	NewEnumerator11                          = 6,
	Liyuuqi_MAX                              = 7,
};

}

