#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lv2_TreasureBox_003

#include "Basic.hpp"

#include "Lv2_TreasureBox_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lv2_TreasureBox_003.Lv2_TreasureBox_003_C
// 0x0000 (0x0EB0 - 0x0EB0)
class ALv2_TreasureBox_003_C final : public ALv2_TreasureBox_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Lv2_TreasureBox_003_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Lv2_TreasureBox_003_C")
	}
	static class ALv2_TreasureBox_003_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALv2_TreasureBox_003_C>();
	}
};
DUMPER7_ASSERTS_ALv2_TreasureBox_003_C;

}

