#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lv4_TreasureBox_001

#include "Basic.hpp"

#include "Lv4_TreasureBox_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lv4_TreasureBox_001.Lv4_TreasureBox_001_C
// 0x0000 (0x0EB0 - 0x0EB0)
class ALv4_TreasureBox_001_C final : public ALv4_TreasureBox_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Lv4_TreasureBox_001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Lv4_TreasureBox_001_C")
	}
	static class ALv4_TreasureBox_001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALv4_TreasureBox_001_C>();
	}
};
DUMPER7_ASSERTS_ALv4_TreasureBox_001_C;

}

