#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: mon_24_BP_World_fly_Patrol

#include "Basic.hpp"

#include "BP_IdleStateFlyingPatrol_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass mon_24_BP_World_fly_Patrol.mon_24_BP_World_fly_Patrol_C
// 0x0000 (0x0420 - 0x0420)
class Umon_24_BP_World_fly_Patrol_C final : public UBP_IdleStateFlyingPatrol_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("mon_24_BP_World_fly_Patrol_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"mon_24_BP_World_fly_Patrol_C")
	}
	static class Umon_24_BP_World_fly_Patrol_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Umon_24_BP_World_fly_Patrol_C>();
	}
};
DUMPER7_ASSERTS_Umon_24_BP_World_fly_Patrol_C;

}

