#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mon_12_1_hidebody

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mon_12_1_hidebody.Mon_12_1_hidebody_C
// 0x0000 (0x0038 - 0x0038)
class UMon_12_1_hidebody_C final : public UAnimNotify
{
public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Mon_12_1_hidebody_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Mon_12_1_hidebody_C")
	}
	static class UMon_12_1_hidebody_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMon_12_1_hidebody_C>();
	}
};
DUMPER7_ASSERTS_UMon_12_1_hidebody_C;

}

