#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: mon_18_BP_World_Passive_New_Black

#include "Basic.hpp"

#include "mon_18_BP_World_Passive_New_Black_classes.hpp"
#include "mon_18_BP_World_Passive_New_Black_parameters.hpp"


namespace SDK
{

// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Amon_18_BP_World_Passive_New_Black_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.OnNotifyEnd_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::OnNotifyEnd_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "OnNotifyEnd_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0");

	Params::mon_18_BP_World_Passive_New_Black_C_OnNotifyEnd_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.OnNotifyBegin_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::OnNotifyBegin_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "OnNotifyBegin_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0");

	Params::mon_18_BP_World_Passive_New_Black_C_OnNotifyBegin_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.OnInterrupted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::OnInterrupted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "OnInterrupted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0");

	Params::mon_18_BP_World_Passive_New_Black_C_OnInterrupted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.OnCompleted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::OnCompleted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "OnCompleted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0");

	Params::mon_18_BP_World_Passive_New_Black_C_OnCompleted_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.OnBlendOut_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::OnBlendOut_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "OnBlendOut_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0");

	Params::mon_18_BP_World_Passive_New_Black_C_OnBlendOut_E391B2DD4C6A6F0CB9BC4CB5A1C7F1A0 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.ExecuteUbergraph_mon_18_BP_World_Passive_New_Black
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::ExecuteUbergraph_mon_18_BP_World_Passive_New_Black(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "ExecuteUbergraph_mon_18_BP_World_Passive_New_Black");

	Params::mon_18_BP_World_Passive_New_Black_C_ExecuteUbergraph_mon_18_BP_World_Passive_New_Black Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function mon_18_BP_World_Passive_New_Black.mon_18_BP_World_Passive_New_Black_C.ChangeHp
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   OldValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   NewValue                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Amon_18_BP_World_Passive_New_Black_C::ChangeHp(float OldValue, float NewValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("mon_18_BP_World_Passive_New_Black_C", "ChangeHp");

	Params::mon_18_BP_World_Passive_New_Black_C_ChangeHp Parms{};

	Parms.OldValue = OldValue;
	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}

}

