#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SFVA_0002

#include "Basic.hpp"

#include "SFVA_0002_classes.hpp"
#include "SFVA_0002_parameters.hpp"


namespace SDK
{

// Function SFVA_0002.SFVA_0002_C.AcceptB110052
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FName&                      QuestId                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AHTPlayerState*                   thePlayer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ASFVA_0002_C::AcceptB110052(const class FName& QuestId, class AHTPlayerState* thePlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SFVA_0002_C", "AcceptB110052");

	Params::SFVA_0002_C_AcceptB110052 Parms{};

	Parms.QuestId = QuestId;
	Parms.thePlayer = thePlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SFVA_0002.SFVA_0002_C.BPOnMainRoleLoadFinished
// (Event, Public, BlueprintEvent)
// Parameters:
// class AHTPlayerState*                   PlayerState                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ASFVA_0002_C::BPOnMainRoleLoadFinished(class AHTPlayerState* PlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SFVA_0002_C", "BPOnMainRoleLoadFinished");

	Params::SFVA_0002_C_BPOnMainRoleLoadFinished Parms{};

	Parms.PlayerState = PlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SFVA_0002.SFVA_0002_C.ExecuteUbergraph_SFVA_0002
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASFVA_0002_C::ExecuteUbergraph_SFVA_0002(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SFVA_0002_C", "ExecuteUbergraph_SFVA_0002");

	Params::SFVA_0002_C_ExecuteUbergraph_SFVA_0002 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SFVA_0002.SFVA_0002_C.OnFurnitureAfterActivated
// (Event, Public, BlueprintEvent)

void ASFVA_0002_C::OnFurnitureAfterActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SFVA_0002_C", "OnFurnitureAfterActivated");

	UObject::ProcessEvent(Func, nullptr);
}

}

