#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StorageCabine_Base_LevelInstance_1

#include "Basic.hpp"

#include "StorageCabine_Base_LevelInstance_1_classes.hpp"
#include "StorageCabine_Base_LevelInstance_1_parameters.hpp"


namespace SDK
{

// Function StorageCabine_Base_LevelInstance_1.StorageCabine_Base_C.BPOnPlayerCustomNortify_Evemt
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FName&                      ID                                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    InValue                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AStorageCabine_Base_C::BPOnPlayerCustomNortify_Evemt(const class FName& ID, const class FString& InValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StorageCabine_Base_C", "BPOnPlayerCustomNortify_Evemt");

	Params::StorageCabine_Base_C_BPOnPlayerCustomNortify_Evemt Parms{};

	Parms.ID = ID;
	Parms.InValue = std::move(InValue);

	UObject::ProcessEvent(Func, &Parms);
}


// Function StorageCabine_Base_LevelInstance_1.StorageCabine_Base_C.ExecuteUbergraph_StorageCabine_Base
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AStorageCabine_Base_C::ExecuteUbergraph_StorageCabine_Base(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StorageCabine_Base_C", "ExecuteUbergraph_StorageCabine_Base");

	Params::StorageCabine_Base_C_ExecuteUbergraph_StorageCabine_Base Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function StorageCabine_Base_LevelInstance_1.StorageCabine_Base_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AStorageCabine_Base_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("StorageCabine_Base_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

