#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_MB_RainMan_State

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum UDS_MB_RainMan_State.UDS_MB_RainMan_State
// NumValues: 0x0007
enum class EUDS_MB_RainMan_State : uint8
{
	NewEnumerator5                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator6                           = 4,
	NewEnumerator7                           = 5,
	UDS_MB_RainMan_MAX                       = 6,
};

}

