#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UW_AwardList_BP

#include "Basic.hpp"

#include "HTGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UW_AwardList_BP.UW_AwardList_BP_C
// 0x0000 (0x0670 - 0x0670)
class UUW_AwardList_BP_C final : public UHTUW_AwardList
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UW_AwardList_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UW_AwardList_BP_C")
	}
	static class UUW_AwardList_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUW_AwardList_BP_C>();
	}
};
DUMPER7_ASSERTS_UUW_AwardList_BP_C;

}

