#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Weapon_Player_Weapon_skin_Skeleton_AnimBlueprint2

#include "Basic.hpp"

#include "BPWeaponAnimBase_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Weapon_Player_Weapon_skin_Skeleton_AnimBlueprint2.Weapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C
// 0x0000 (0x1120 - 0x1120)
class UWeapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C final : public UBPWeaponAnimBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Weapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Weapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C")
	}
	static class UWeapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWeapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C>();
	}
};
DUMPER7_ASSERTS_UWeapon_Player_Weapon_skin_Skeleton_AnimBlueprint2_C;

}

